spring.application.name=bff-agendador-tarefas
server.port=8084

# Use apenas minusculas e hifens
usuario.url=http://usuario:8081/usuario
agendador-de-tarefas.url=http://agendador-tarefas:8082/tarefas
notificacao.url=http://notificacao:8083/email

cron.horario=0 0/5 * * * ?
usuario.email=admin@admin.com
usuario.senha=1234

# Enable Apache HttpClient 5 for Feign (supports PATCH)
feign.httpclient.enabled=true