spring.application.name=bff-agendador-tarefas

server.port = 8084

usuario.url = localhost:8081/usuario
Agendador-de-Tarefas.url = http://localhost:8082/tarefas
notificacao.url = localhost:8083/email


cron.horario = 0 0/5 * * * ?

usuario.email = admin@admin.com
usuario.senha = 1234

resilience4j.circuitbreaker.instances.meuServico.sliding-window-size=10
resilience4j.circuitbreaker.instances.meuServico.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.meuServico.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.meuServico.permitted-number-of-calls-in-half-open-state=3